#!/usr/bin/env python3
"""
convert_rom.py — converts a .gb ROM into a Monkey C source file.

The ROM is embedded as ByteArray literals compiled directly into the .prg.
At runtime, each chunk() call is a fast constant-pool copy — no parsing.

Usage:
    python3 tools/convert_rom.py "resources/rom/Tetris (World) (Rev 1).gb" source/RomData.mc

64 functions × 512 bytes = 32768 bytes (32KB MBC0 ROM).
"""

import sys

CHUNK_SIZE = 512
TOTAL_BYTES = 32768

def convert(input_path, output_path):
    with open(input_path, "rb") as f:
        rom_data = f.read()

    print(f"ROM:   {input_path}")
    print(f"Size:  {len(rom_data)} bytes")

    if len(rom_data) != TOTAL_BYTES:
        print(f"WARNING: Expected {TOTAL_BYTES} bytes for MBC0, got {len(rom_data)}")

    chunks = [rom_data[i:i + CHUNK_SIZE] for i in range(0, len(rom_data), CHUNK_SIZE)]
    print(f"Chunks: {len(chunks)} × {CHUNK_SIZE} bytes")

    with open(output_path, "w") as out:
        out.write("// Auto-generated by tools/convert_rom.py — do not edit.\n")
        out.write("// Tetris (World) ROM embedded as compiled ByteArray literals.\n\n")
        out.write("module RomData {\n\n")
        out.write(f"    const CHUNK_SIZE = {CHUNK_SIZE};\n")
        out.write(f"    const NUM_CHUNKS = {len(chunks)};\n\n")

        for idx, chunk in enumerate(chunks):
            hex_vals = ", ".join(f"0x{b:02X}" for b in chunk)
            out.write(f"    function chunk{idx}() {{\n")
            out.write(f"        return [{hex_vals}]b;\n")
            out.write(f"    }}\n\n")

        out.write("}\n")

    print(f"Written: {output_path}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.gb> <output.mc>")
        sys.exit(1)
    convert(sys.argv[1], sys.argv[2])
